# /// PLAYER ///

## getPlayersList
GET http://localhost:8080/api/player HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE2NzcwNTYyNTQsImV4cCI6MTY3NzA5MjI1NH0.5_ugTus37UMgUgoPSGPp-EXICpOlF0lCCKTHNahIQo2MWg79HV3e4tvwbiQbwwdIQpLHq9m4guiO-Cnz4KlEgg
###
## getPlayersList
GET http://localhost:8080/api/player/1/hasType HTTP/1.1
Content-Type: application/json
###
## getPlayersList
GET http://localhost:8080/api/player/1 HTTP/1.1
Content-Type: application/json
###
## addTypePlayer
POST http://localhost:8080/api/player/1/type/1 HTTP/1.1
Content-Type: application/json
###
## getPlayerDbByEmail
GET http://localhost:8080/api/player/user1@gmail.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE2NzcwNTc1ODYsImV4cCI6MTY3NzA5MzU4Nn0.vdVOthA6fOc_YrdFRJVUZ_fGeDRcXlZbaOPJaFJ06ZdrkQiajcbGULnTwm9is1GDXyeWilGHxjo6M44wDMWXqg
###