# /// PLAYER ///

## getPlayersList
GET http://localhost:8080/api/player HTTP/1.1
Content-Type: application/json
###
## getPlayersList
GET http://localhost:8080/api/player/1/hasType HTTP/1.1
Content-Type: application/json
###
## getPlayersList
GET http://localhost:8080/api/player/1 HTTP/1.1
Content-Type: application/json
###